Add composite test action

diff --git a/devbox/molecule/config/Makefile b/devbox/molecule/config/Makefile
--- a/devbox/molecule/config/Makefile
+++ b/devbox/molecule/config/Makefile
@@ -2,7 +2,6 @@
 
 UV := $(shell if [ -f pyproject.toml ]; then echo uv; else echo "uv --directory {{.Virtenv}}"; fi)
 MOLECULE_SCENARIO ?= default
-MOLECULE_REVISION ?= $$(git rev-parse --abbrev-ref HEAD)
 MOLECULE_LOGDIR ?= /tmp/logs
 UBUNTU_RELEASE ?= noble
 UBUNTU_KVM_IMAGE = https://cloud-images.ubuntu.com/${UBUNTU_RELEASE}/current/${UBUNTU_RELEASE}-server-cloudimg-amd64.img
@@ -14,7 +13,13 @@ REQUIREMENTS = requirements.yml
 ROLE_DIR = roles
 ROLE_FILE = roles.yml
 
+BASE_SHA ?= $$(git rev-parse origin)
+HEAD_SHA ?= $$(git rev-parse HEAD)
+BASE_VERSION := $$(git show $(BASE_SHA):galaxy.yml | yq -r .version)
+HEAD_VERSION := $$(git show $(HEAD_SHA):galaxy.yml | yq -r .version)
+
 LOGIN_ARGS ?=
+VERSION_CHECK_ARGS ?=
 
 init overwrite:
 	@mkdir -p .github/workflows
@@ -55,6 +60,8 @@ build: requirements
 	if [ -f "${GALAXY_FILE}" ]; then \
 		${UV} build; \
 		@git status --porcelain | wc -l | grep -q '^0$$' || (echo "Uncommitted build detected, please run build stage and commit changes" && exit 1); \
+	else
+		echo "No ${GALAXY_FILE} found, skipping build"; \
 	fi
 
 update:
@@ -67,7 +74,6 @@ endif
 
 test dependency create prepare converge idempotence side-effect verify destroy cleanup reset list login:
 		find .venv -type d -name ansible_collections | xargs -r -- rm -r
-		MOLECULE_REVISION=${MOLECULE_REVISION} \
 		MOLECULE_KVM_IMAGE=${MOLECULE_KVM_IMAGE} \
 		MOLECULE_LOGDIR=${MOLECULE_LOGDIR} \
 		molecule $@ -s ${MOLECULE_SCENARIO} ${LOGIN_ARGS};
@@ -90,3 +96,22 @@ publish: build
 			ansible-galaxy collection publish --api-key ${GALAXY_API_KEY} \
 				"$${COLLECTION_NAMESPACE}-$${COLLECTION_NAME}-$${COLLECTION_VERSION}.tar.gz"
 	fi
+
+version-check:
+		# Validate semver format
+		if ! echo "$(HEAD_VERSION)" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$'; then
+			echo "$(HEAD_VERSION) does not follow standard semver format (X.Y.Z)"
+			exit 1
+		fi
+		# Check version is updated
+		if [ "$(BASE_VERSION)" = "$(HEAD_VERSION)" ]; then
+			echo "::error title=Version Not Updated::Version has not been updated in galaxy.yml (still $(BASE_VERSION))"
+			exit 1
+		fi
+		# Verify version update sequence
+		LOWER_VERSION=$(printf '%s\n' "$BASE_VERSION" "$HEAD_VERSION" | sort -V | head -n1)
+		if [ "$(LOWER_VERSION)" = "$(HEAD_VERSION)" ]; then
+			echo "New version ($(HEAD_VERSION)) must be greater than base version ($(BASE_VERSION))"
+			exit 1
+		fi
+		echo "Version updated from $(BASE_VERSION) to $(HEAD_VERSION)"
