Fix ci tests for version check logic

diff --git a/.github/workflows/devbox.yml b/.github/workflows/devbox.yml
--- a/.github/workflows/devbox.yml
+++ b/.github/workflows/devbox.yml
@@ -162,6 +162,8 @@ jobs:
         env:
           BASE_SHA: ${{ github.event.pull_request.base.sha }}
           HEAD_SHA: ${{ github.event.pull_request.head.sha }}
+          GALAXY_PATH: tests/collection/galaxy.yml
+          GALAXY_FILE: ${{ github.workspace }}/galaxy.yml
 
   version-unchanged:
     runs-on: ubuntu-latest
@@ -196,7 +198,14 @@ jobs:
         env:
           BASE_SHA: ${{ github.event.pull_request.head.sha }}
           HEAD_SHA: ${{ github.event.pull_request.head.sha }}
-        id: check_fail
+          GALAXY_PATH: tests/collection/galaxy.yml
+          GALAXY_FILE: ${{ github.workspace }}/galaxy.yml
+
+      - name: Validate version-check result
+        if: steps.check_fail.outcome == 'success'
+        run: |
+          echo "Version check dit not signal failure on missing version update."
+          exit 1
 
       - name: Validate ${{matrix.build}} version-check result
         if: steps.check_fail.outcome == 'success'
